name = "DiffEqGPU"
uuid = "071ae1c0-96b5-11e9-1965-c90190d839ea"
authors = ["Chris Rackauckas", "JuliaDiffEq"]
version = "1.9.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
CUDA = "1, 2.0"
DiffEqBase = "6.5"
ForwardDiff = "0.10"
KernelAbstractions = "0.2, 0.3, 0.4"
julia = "1.5"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["ForwardDiff", "OrdinaryDiffEq", "SafeTestsets", "StochasticDiffEq", "Test", "Unitful", "Random"]
