name = "DiffEqGPU"
uuid = "071ae1c0-96b5-11e9-1965-c90190d839ea"
authors = ["Chris Rackauckas", "SciML"]
version = "3.8.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
AMDGPUExt = ["AMDGPU"]
CUDAExt = ["CUDA"]
JLArraysExt = ["JLArrays"]
MetalExt = ["Metal"]
oneAPIExt = ["oneAPI"]

[compat]
AMDGPU = "1, 2"
Adapt = "4"
CUDA = "5"
ChainRulesCore = "1"
DiffEqBase = "6.122"
DocStringExtensions = "0.9"
ForwardDiff = "0.10.38, 1"
GPUArraysCore = "0.2"
JLArrays = "0.1, 0.2, 0.3"
KernelAbstractions = "0.9"
LinearSolve = "3"
Metal = "1"
MuladdMacro = "0.2"
Parameters = "0.12"
RecursiveArrayTools = "3"
SciMLBase = "2.92"
Setfield = "1"
SimpleDiffEq = "1"
StaticArrays = "1"
TOML = "1"
ZygoteRules = "0.2"
julia = "1.10"
oneAPI = "2"

[extras]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
